language: ruby # use a ruby environment
rvm:
  - 2.4.4

before_script:
<<<<<<< HEAD
 - chmod +x ./cibuild
 - chmod +x ./deploy.sh


=======
 - chmod +x ./script/cibuild
 - chmod +x ./deploy.sh

>>>>>>> trying setup
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "acb451626639"
  - COMMIT_AUTHOR_EMAIL: "travis@frclabviewtutorials.com"
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# branch whitelist, only for GitHub Pages
branches:
  only:
<<<<<<< HEAD
  - master   # build the master branch and push to gh-pages
=======
  - gh-pages     # test the gh-pages branch
>>>>>>> trying setup

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false